# Generated by Django 2.2.26 on 2022-02-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20220204_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'pages'},
        ),
    ]
