# Generated by Django 2.2.26 on 2022-02-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20220206_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
